language: node_js
node_js:
  - 0.6
after_install:
  - "curl -L https://github.com/rameshmaveric/NodeMocha.git | /bin/sh"
before_script:
 - npm cache clean
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master
